### ISSUE TITLE
Closed app before mp4 was saved and I lost it

### ISSUE THREAD

**Issue by acoppes** [kevglass/floom#17]
I recorded a video and after I picked where to save it I closed the app since I wasn't going to record another video for the moment but I lost the first one because it takes some time to save the mp4 file. Maybe this could be fixed by just showing the save progress or something like that, not sure, but just wanted to report the issue.

Thanks

**Comment by kevglass** [comment]
Thanks will get it asap.

**Comment by kevglass** [comment]
Added a save indicator in 1.1.2
