### ISSUE TITLE
Javascript error when trying to record

### ISSUE THREAD

**Issue by rgarat** [kevglass/floom#3]
I  was trying to test the app, and when starting to record it gave this error.
After clicking accept it just offered to save the resulting video

![image](https://user-images.githubusercontent.com/488894/210577868-1df7c028-430a-4fcb-b129-b53eca6beaad.png)

**Comment by prof-nobody** [comment]
Encountered the same. It also moved the Stop Recording button inside the view window and shows said button in the recording output. This is only when moving it to record a different display than the primary display. No issues or errors on the primary display for me.

**Comment by prof-nobody** [comment]
@rgarat update to the latest. That error only seems to be version 1.0.5 and lower. https://cokeandcode.com/floom/ I just did the update and it is working now without issue.

**Comment by prof-nobody** [comment]
Huh interesting issue I am not encountering. If you record on one monitor then move to another monitor it starts having issues. This could be something to do with having different resolutions between the monitors. Will test that

**Comment by prof-nobody** [comment]
Issue seems intermittent in when it wants to happen. I moved it between 3 monitors, two with the same size and one smaller resolution. Other but I am noticing is that the recording window will expand or contract occasionally. Normally with a change to a different resolution. If you stop recording it is fine the next time you hit record. Will open a different bug report for this.

**Comment by rgarat** [comment]
I was using 1.0.6 and it showed the error
I had moved the recorder from my main monitor 4k to my other one 1680x1050 no idea if this gives any clue

**Comment by kevglass** [comment]
1.0.7 fixed this one.
