### ISSUE TITLE
Recording bounds red rectangle has wrong size

### ISSUE THREAD

**Issue by rgarat** [kevglass/floom#6]
The red rectangle that appears when you are recording gets scaled wrong depending on monitor resolution I guess.

My main monitor is 4k, the secondary one is 1680x1050 and this is being recorded on the secondary monitor

![image](https://user-images.githubusercontent.com/488894/210606231-ffe0fcec-cb7e-49f3-92b3-dd46db67a4a7.png)

**Comment by prof-nobody** [comment]
Did it change dimensions when it started recording? If you hit stop and start it again does it correct itself? If so I believe this is a duplicate of [issue 4](https://github.com/kevglass/floom/issues/4)

**Comment by rgarat** [comment]
Yes, I think it is the same issue.
