### ISSUE TITLE
Request: Allow None as an option for webcam and mic

### ISSUE THREAD

**Issue by rgarat** [kevglass/floom#7]
Hi, this is shaping up as a super nice tool.

For now at least my use case is more as a quick way to share video and at least on windows there is nothing as easy as the screen recorder that you invoke with shift+command+5  on mac.

This would be an awesome replacement for that on windows, but I would love if you could select not adding a webcam feed so that I can freely record small videos to share. Also disabling the sound recording and having a system sounds options would be awesome.

Thanks

**Comment by prof-nobody** [comment]
System sound request has been captured here [Record System Sound](https://github.com/kevglass/floom/issues/2) it is in progress.
Suggestion - You can leave the webcam out of the frame and not record the video of it and mute your microphone for not picking up ambient sound.

**Comment by kevglass** [comment]
In 1.0.8
