### ISSUE TITLE
Windows playback doesn't work

### ISSUE THREAD

**Issue by prof-nobody** [kevglass/floom#8]
In testing of the 1.0.8 version there did seem to be an issue with Windows playback if there was audio from the system. If there was no system audio there doesn't seem to be an issue with playback.

**Comment by prof-nobody** [comment]
Just confirmed in a longer video where I do speak into the microphone. It will playback on windows but if there is system audio it errors out.

**Comment by kevglass** [comment]
Think this was because of dual audio inputs. Mixed in 1.0.9
