### ISSUE TITLE
Bug: Recording window still resizes on record in 1.0.9

### ISSUE THREAD

**Issue by rgarat** [kevglass/floom#9]
The first time recording after moving the window from my main to secondary monitor the red square is shown incorrectly, the second time it seems to work better

https://user-images.githubusercontent.com/488894/210835074-f2e18ef8-1307-493e-8114-3d01c5c15d48.mp4

**Comment by kevglass** [comment]
Put another attempt in to resolve this in 1.1.0

**Comment by kevglass** [comment]
Try this one again in 1.1.0 - see if the same issue, still haven't been able to reproduce on my screens here.

**Comment by prof-nobody** [comment]
Window expands but then quickly snaps back to the size it should be showing in my testing so far

**Comment by rgarat** [comment]
It is still happening on 1.1.0, its starts smaller, then goes to the right size, on second records it works fine. 
The saved data corresponds to the smaller red square, if you launch the app again it will start smaller.

https://user-images.githubusercontent.com/488894/211162092-07a83887-c0ad-49ad-8a2c-be79ca68f088.mp4

**Comment by kevglass** [comment]
Yeah thats what I'd expect at the moment, it was a test in the version to see if it could be corrected. Turns out setting the size doesn't work correct before the window is reshown.

**Comment by kevglass** [comment]
Should be instant recorrect in 1.1.2 - its a bug in a electron so theres always going to be a tiny pause.
